# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty


# Setup
title: Performance Hall Docs
tagline: 'The Home of Logan Center Tech Knowledge'
description: 'The hub of all information regarding the various domains of the Performance Hall staff. </br> If there are other things you would like to see here email: </br> <a href="mailto:kpmccornack@gmail.com">kpmccornack@gmail.com</a>'
url:                 performancehall.github.io
baseurl:             ''
paginate:            1

# About/contact
author:
  name:              Kyle McCornack
  url:
  email:             kpmccornack@gmail.com

# Custom vars
version:             1.1.0

audio:
    - title: A1 Checklist
      url: /2016/01/03/a1-checklist.html
    - title: Audio Glossary
      url: /2015/12/26/audio-glossary.html
    - title: Archival Recording Instructions and Standards
      url: /2015/12/29/archival_instructions.html
    - title: Audio Equipment and Set Up
      url: /2015/12/26/equipment-and-setup.html
    - title: Getting Sound From a Mic to the Mains
      url: /2015/12/29/mic-to-mains.html
    - title: Handheld Tascam Tutorial
      url: /2015/12/29/handheld_tascam_tutorial.html
    - title: Microphone List
      url: /2015/12/26/microphone-list.html
    - title: Setting Up a Board Feed For a Videographer
      url: /2016/01/02/board-feed-for-videographer.html
    - title: Setting Up a DI-Box
      url: /2015/12/29/setting-up-a-di-box.html
    - title: Setting Up Monitors
      url: /2015/12/30/setting-up-monitors.html
    - title: Seven System Dwarves
      url: /2015/12/29/seven-system-dwarves.html

hall_lighting:
    - title: Followspot Guide
      url: /2016/01/03/followspot-guide.html
    - title: General Information
      url: /2016/01/03/lighting-info.html
    - title: Performance Hall Magic Sheet
      url: /2016/01/03/ph-magic-sheet-summer-2015.html
    - title: Performance Hall Channel Hookup
      url: /assets/lighting_channel_hookup.pdf
    - title: Performance Hall Rep Plot
      url: /assets/ph_rep_plot.pdf
    - title: Performance Hall Instrument Schedule
      url: /assets/lighting_instrument_schedule.pdf
    - title: Node Configuration Instructions
      url: /2016/01/03/node-configuration.html

penthouse_lighting:
    - title: Penthouse Channel Hookup
      url: /assets/penthouse_channel_hookup.pdf
    - title: Penthouse Lightboard Cheat Sheet
      url: /2016/01/03/penthouse-lightboard-cheatsheet.html

tech:
    - title: Projection Cheat Sheet
      url: /2015/10/03/projection-cheat-sheet.html
    - title: Tech Brochure
      url: /assets/tech_brochure.pdf
    - title: Event Rider Sheet
      url: /assets/event_rider_sheet.pdf
    - title: Grand Curtain Installation Tutorial
      url: /_posts/2016-01-21-grand-tutorial.html
    - title: A Guide to Laying and Striking Marley
      url: /2016/04/12/marley-guide.html
    - title: Stagehand Guide
      url: /2016/04/12/stagehand-guide.html
    - title: Stage Terminology
      url: /2016/04/12/stage-terminology.html
    - title: Soft Goods Guide
      url: /2016/04/12/soft-goods-guide.html
    - title: Genie Use and Safety
      url: /2016/04/12/genie-guide.html

duties:
    - title: General Duties
      url: /2016/04/12/general-duties.html
    - title: Stage Manager Duties
      url: /2016/04/12/stage-manager-duties.html
    - title: Audio Board Operator Duties
      url: /2016/04/12/audio-duties.html
    - title: Lighting Board Operator Duties
      url: /2016/04/12/lighting-duties.html
    - title: Stagehand Duties
      url: /2016/04/12/stagehand-duties.html

drawings:
    - title: Performance Hall East Perspective
      url: /assets/ph_east_perspective.pdf
    - title: Performance Hall Rigging East Perspective
      url: /assets/ph_rigging_east.pdf
    - title: Performance Hall Lighting West Perspective
      url: /assets/ph_lighting_west.jpg
