gems: [jekyll-paginate]

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.

permalink:           pretty

# Setup
title: Performance Hall Docs
tagline: 'The Home of Logan Center Tech Knowledge'
description: 'The hub of all information regarding the various domains of the Performance Hall staff. </br> If there are other things you would like to see here, send an email with the subject line [WEBSITE] to us at: </br> <a href="mailto:hunterkorgel@uchicago.edu">hunterkorgel@uchicago.edu</a> <a href="mailto:kpmccornack@gmail.com">kpmccornack@gmail.com</a>'
url:                 performancehall.github.io
baseurl:             ''
paginate:            1

# About/contact
author:
  name:              Kyle McCornack, Hunter Korgel
  url:
  email:             kpmccornack@gmail.com, hunterkorgel@uchicago.edu

# Custom vars
version:             1.2.0

audio:
    - title: Audio Glossary
      url: /audio/audio-glossary.html
    - title: Archival Recording Instructions and Standards
      url: /audio/archival-instructions.html
    - title: Audio Equipment and Set Up
      url: /audio/equipment-and-setup.html
    - title: Getting Sound From a Mic to the Mains
      url: /audio/mic-to-mains.html
    - title: Handheld Tascam Tutorial
      url: /audio/handheld-tascam-tutorial.html
    - title: Microphone List
      url: /audio/microphone-list.html
    - title: Setting Up a Board Feed For a Videographer
      url: /audio/board-feed-for-videographer.html
    - title: Setting Up a DI-Box
      url: /audio/setting-up-a-di-box.html
    - title: Setting Up Monitors
      url: /audio/setting-up-monitors.html
    - title: Seven System Dwarves
      url: /audio/seven-system-dwarves.html

lighting_hall:
    - title: Followspot Guide
      url: /lighting/followspot-guide.html
    - title: General Information
      url: /lighting/lighting-info.html
    - title: Performance Hall Magic Sheet
      url: /assets/lighting/hall-magic-sheet.pdf
    - title: Performance Hall Channel Hookup
      url: /assets/lighting/hall-channel-hookup.pdf
    - title: Performance Hall Rep Plot
      url: /assets/lighting/hall-rep-plot.pdf
    - title: Performance Hall Instrument Schedule
      url: /assets/lighting/hall-instrument-schedule.pdf
    - title: Node Configuration Instructions
      url: /lighting/node-configuration.html
    - title: Lighting Cheatsheet
      url: /assets/lighting/hall-lighting-cheatsheet.pdf
    - title: Lighting Basics
      url: /lighting/lighting-basics.html

lighting_penthouse:
    - title: Penthouse Channel Hookup
      url: /assets/lighting/penthouse_channel_hookup.pdf

video:
    - title: Projection Cheat Sheet
      url: /video/projection-cheat-sheet.html
    - title: Overflow Video Streams
      url: /video/overflow-video-streams.html
    - title: Video Rack Tutorial
      url: /video/video-rack-guide.html

stage:
    - title: Grand Curtain Guide
      url: /stage/grand-curtain-guide.html
    - title: Marley Guide
      url: /stage/marley-guide
    - title: Genie Guide
      url: /stage/genie-guide.html
    - title: Soft Goods Guide
      url: /stage/soft-goods-guide.html

recording:
    - title: Handheld Tascam tutorial
      url: /recording/handheld-tascam-tutorial.html

checklists:
    - title: A1 Checklist
      url: /checklists/a1-checklist.html
    - title: LX Checklist
      url: /checklists/lighting-checklist.html
    - title: SM Checklist
      url: /checklists/stage-manager-checklist.html

employees:
    - title: Tech Manual
      url: /employees/tech-manual.html
    - title: Emergency Plan
      url: /assets/employees/emergency-plan.pdf

spaces_hall:
    - title: Performance Hall Tech Brochure
      url: /assets/spaces/hall/hall-tech-brochure.pdf
    - title: Blank Stage Plot
      url: /assets/spaces/hall/stage-plot-blank.jpg
    - title: Hall Seating Chart
      url: /assets/spaces/hall/hall-seating-chart.pdf
    - title: Rigging East Perspective
      url: /assets/spaces/hall/hall-rigging-east-perspective.pdf
    - title: Projection East Perspective
      url: /assets/spaces/hall/hall-projection-east-perspective.pdf
    - title: Lighting West Perspective
      url: /assets/spaces/hall/hall-lighting-west-perspective.jpg
    - title: Lighting Measurements
      url: /assets/spaces/hall/hall-lighting-measurements.png
    - title: Audio South Perspective
      url: /assets/spaces/hall/hall-audio-south-perspective.pdf
    - title: Banners East Perspective
      url: /assets/spaces/hall/hall-banners-east-perspective.pdf
    - title: General East Perspective
      url: /assets/spaces/hall/hall-general-east-perspective.pdf
    - title: Load In Map
      url: /assets/spaces/hall/hall-load-in-map.pdf
    - title: Ground Plan
      url: /assets/spaces/hall/hall-ground-plan.jpg

spaces_penthouse:
    - title: Penthouse Tech Brochure
      url: /assets/spaces/penthouse/penthouse-tech-brochure.pdf
    - title: Orchestra Layout
      url: /assets/spaces/penthouse/penthouse-orchestra.tif
    - title: Reception Layout
      url: /assets/spaces/penthouse/penthouse-reception.tif
    - title: Workshop Layout
      url: /assets/spaces/penthouse/penthouse-workshop.tif
    - title: Penthouse Measurements
      url: /assets/spaces/penthouse/penthouse-measurements.tif
    - title: Penthouse Lighting Instrument Plot
      url: /assets/spaces/penthouse/penthouse-lighting-plot.pdf

spaces_201:
    - title: Film Screening Room Tech Brochure
      url: /assets/spaces/201/201-tech-brochure.pdf
    - title: Screening Room Floor Plan
      url: /assets/spaces/201/201-floor-plan.pdf
