# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title: Performance Hall Docs
tagline: 'A fount of Logan Center Knowledge'
description: 'The hub of all information regarding the various domains of the Performance Hall staff. </br> If there are other things you would like to see here email: </br> <a href="mailto:kpmccornack@gmail.com">kpmccornack@gmail.com</a>'
url:                 performancehall.github.io
baseurl:             ''
paginate:            1

# About/contact
author:
  name:              Kyle McCornack
  url:
  email:             kpmccornack@gmail.com

# Custom vars
version:             1.0.0

audio:
    - title: Audio Basics Guide
      url: /assets/audio_basics_guide.pdf

lighting:
    - title: Performance Hall Magic Sheet
      url: /assets/ph_magic_sheet.pdf

tech:
    - title: Projection Cheat Sheet
      url: /2015/10/03/projection-cheat-sheet.html

drawings:
    - title: Performance Hall East Perspective
      url: /assets/ph_east_perspective.pdf
