gems: [jekyll-paginate]

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title: Performance Hall Docs
tagline: 'The Home of Logan Center Tech Knowledge'
description: 'The hub of all information regarding the various domains of the Performance Hall staff. </br> If there are other things you would like to see here email: </br> <a href="mailto:hunterkorgel@uchicago.edu">hunterkorgel@uchicago.edu</a> <a href="mailto:kpmccornack@gmail.com">kpmccornack@gmail.com</a>'
url:                 performancehall.github.io
baseurl:             ''
paginate:            1

# About/contact
author:
  name:              Kyle McCornack, Hunter Korgel
  url:
  email:             kpmccornack@gmail.com, hunterkorgel@uchicago.edu

# Custom vars
version:             1.2.0

audio:
    - title: A1 Checklist
      url: /audio_a1_checklist.html
    - title: Audio Glossary
<<<<<<< HEAD
      url: /_audio/audio_glossary.html
=======
      url: /audio/audio_glossary.html
>>>>>>> 019e223988e43ec12212f3470a1ef5bd3683b904
    - title: Archival Recording Instructions and Standards
      url: /audio/archival_instructions.html
    - title: Audio Equipment and Set Up
      url: /audio/equipment_and_setup.html
    - title: Getting Sound From a Mic to the Mains
      url: /audio/mic_to_mains.html
    - title: Handheld Tascam Tutorial
      url: /audio/handheld_tascam_tutorial.html
    - title: Microphone List
      url: /audio/microphone_list.html
    - title: Setting Up a Board Feed For a Videographer
      url: /audio/board_feed_for_videographer.html
    - title: Setting Up a DI-Box
      url: /audio/setting_up_a_di_box.html
    - title: Setting Up Monitors
      url: /audio/setting_up_monitors.html
    - title: Seven System Dwarves
      url: /audio/seven_system_dwarves.html

lighting_hall:
    - title: Followspot Guide
      url: /2016/01/03/followspot-guide.html
    - title: General Information
      url: /2016/01/03/lighting-info.html
    - title: Performance Hall Magic Sheet
      url: /2016/01/03/ph-magic-sheet-summer-2015.html
    - title: Performance Hall Channel Hookup
      url: /assets/lighting_channel_hookup.pdf
    - title: Performance Hall Rep Plot
      url: /assets/ph_rep_plot.pdf
    - title: Performance Hall Instrument Schedule
      url: /assets/lighting_instrument_schedule.pdf
    - title: Node Configuration Instructions
      url: /2016/01/03/node-configuration.html

lighting_penthouse:
    - title: Penthouse Channel Hookup
      url: /assets/penthouse_channel_hookup.pdf
    - title: Penthouse Lightboard Cheat Sheet
      url: /2016/01/03/penthouse-lightboard-cheatsheet.html

tech:
    - title: Projection Cheat Sheet
      url: /2015/10/03/projection-cheat-sheet.html
    - title: Tech Brochure
      url: /assets/tech_brochure.pdf
    - title: Event Rider Sheet
      url: /assets/event_rider_sheet.pdf
    - title: Grand Curtain Installation Tutorial
      url: /_posts/2016-01-21-grand-tutorial.html
    - title: A Guide to Laying and Striking Marley
      url: /2016/04/12/marley-guide.html
    - title: Stagehand Guide
      url: /2016/04/12/stagehand-guide.html
    - title: Stage Terminology
      url: /2016/04/12/stage-terminology.html
    - title: Soft Goods Guide
      url: /2016/04/12/soft-goods-guide.html
    - title: Genie Use and Safety
      url: /2016/04/12/genie-guide.html
    - title: Video Overflow Setup
      url: /2016/03/08/overflow-video-streams.html

duties:
    - title: General Duties
      url: /2016/04/12/general-duties.html
    - title: Stage Manager Duties
      url: /2016/04/12/stage-manager-duties.html
    - title: Audio Board Operator Duties
      url: /2016/04/12/audio-duties.html
    - title: Lighting Board Operator Duties
      url: /2016/04/12/lighting-duties.html
    - title: Stagehand Duties
      url: /2016/04/12/stagehand-duties.html

drawings:
    - title: Performance Hall East Perspective
      url: /assets/ph_east_perspective.pdf
    - title: Performance Hall Rigging East Perspective
      url: /assets/ph_rigging_east.pdf
    - title: Performance Hall Lighting West Perspective
      url: /assets/ph_lighting_west.jpg
