gems: [jekyll-paginate]

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.

permalink:           pretty

# Setup
title: Performance Hall Docs
tagline: 'The Home of Logan Center Tech Knowledge'
description: 'The hub of all information regarding the various domains of the Performance Hall staff. </br> If there are other things you would like to see here, send an email with the subject line [WEBSITE] to us at: </br> <a href="mailto:hunterkorgel@uchicago.edu">hunterkorgel@uchicago.edu</a> <a href="mailto:kpmccornack@gmail.com">kpmccornack@gmail.com</a>'
url:                 performancehall.github.io
baseurl:             ''
paginate:            1

# About/contact
author:
  name:              Kyle McCornack, Hunter Korgel
  url:
  email:             kpmccornack@gmail.com, hunterkorgel@uchicago.edu

# Custom vars
version:             1.2.0

audio:
    - title: A1 Checklist
      url: /audio/a1-checklist.html
    - title: Audio Duties
      url: /audio/audio-duties.html
    - title: Audio Glossary     
      url: /audio/audio-glossary.html
    - title: Archival Recording Instructions and Standards
      url: /audio/archival-instructions.html
    - title: Audio Equipment and Set Up
      url: /audio/equipment-and-setup.html
    - title: Getting Sound From a Mic to the Mains
      url: /audio/mic-to-mains.html
    - title: Handheld Tascam Tutorial
      url: /audio/handheld-tascam-tutorial.html
    - title: Microphone List
      url: /audio/microphone-list.html
    - title: Setting Up a Board Feed For a Videographer
      url: /audio/board-feed-for-videographer.html
    - title: Setting Up a DI-Box
      url: /audio/setting-up-a-di-box.html
    - title: Setting Up Monitors
      url: /audio/setting-up-monitors.html
    - title: Seven System Dwarves
      url: /audio/seven-system-dwarves.html


lighting_hall:
    - title: Lighting Duties
      url: /lighting/lighting-duties.html
    - title: Followspot Guide
      url: /lighting/followspot-guide.html
    - title: General Information
      url: /lighting/lighting-info.html
    - title: Performance Hall Magic Sheet
      url: /lighting/ph-magic-sheet-summer-2015.html
    - title: Performance Hall Channel Hookup
      url: /assets/lighting/lighting_channel_hookup.pdf
    - title: Performance Hall Rep Plot
      url: /assets/lighting/ph_rep_plot.pdf
    - title: Performance Hall Instrument Schedule
      url: /assets/lighting/lighting_instrument_schedule.pdf
    - title: Node Configuration Instructions
      url: /lighting/node-configuration.html
    - title: Genie Guide
      url: /lighting/genie-guide.html

lighting_penthouse:
    - title: Penthouse Channel Hookup
      url: /assets/lighting/penthouse_channel_hookup.pdf
    - title: Penthouse Lightboard Cheat Sheet
      url: /lighting/penthouse-lightboard-cheatsheet.html

video:
    - title: Projection Cheat Sheet
      url: /video/projection-cheat-sheet.html
    - title: Overflow Video Streams
      url: /video/overflow-video-streams.html
    - title: Video Rack Tutorial
      url: /video/video-rack-guide.html

stage:
    - title: Grand Curtain Guide
      url: /stage/grand-curtain-guide.html
    - title: Marley Guide
      url: /stage/marley-guide
    - title: Stage Manager Duties
      url: /stage/stage-manager-duties.html
    - title: Stage Terminology
      url: /stage/stage-terminology.html
    - title: Stagehand Guide
      url: /stage/stagehand-guide.html
    - title: Genie Guide
      url: /stage/genie-guide.html
    - title: Soft Goods Guide
      url: /stage/soft-goods-guide.html
    - title: Stagehand Duties
      url: /stage/stagehand-duties.html

recording:
    - title: Handheld Tascam tutorial
      url: /recording/handheld-tascam-tutorial.html

employees:
    - title: General Duties
      url: /employees/general-duties.html
    - title: Stage Terminology
      url: /employees/stage-terminology.html

spaces_tech:
    - title: Tech Brochure
      url: /assets/spaces/tech_brochure.pdf
    - title: Event Rider Sheet
      url: /assets/spaces/event_rider_sheet.pdf

spaces_drawings:
    - title: Performance Hall East Perspective
      url: /assets/spaces/ph_east_perspective.pdf
    - title: Performance Hall Rigging East Perspective
      url: /assets/spaces/ph_rigging_east.pdf
    - title: Performance Hall Lighting West Perspective
      url: /assets/spaces/ph_lighting_west.jpg
