# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title: Performance Hall Docs
tagline: 'A fount of Logan Center Knowledge'
description: 'The hub of all information regarding the various domains of the Performance Hall staff. </br> If there are other things you would like to see here email: </br> <a href="mailto:kpmccornack@gmail.com">kpmccornack@gmail.com</a>'
url:                 performancehall.github.io
baseurl:             ''
paginate:            1

# About/contact
author:
  name:              Kyle McCornack
  url:
  email:             kpmccornack@gmail.com

# Custom vars
version:             1.1.0

audio:
    - title: Audio Basics Guide
      url: /assets/audio_basics_guide.pdf
    - title: Archival Recording Standards
      url: /assets/archival_recording_standards.pdf
    - tite: Handheld Tascam Tutorial
      url: /assets/handheld_tascam_tutorial.pdf

lighting:
    - title: Performance Hall Magic Sheet
      url: /assets/ph_magic_sheet.pdf
    - title: Penthouse Lighting Board Cheat Sheet
      url: /assets/lighting_board_cheat_sheet.pdf
    - title: Node Configuration Instructions
      url: /assets/lighting_node_config.pdf

tech:
    - title: Projection Cheat Sheet
      url: /2015/10/03/projection-cheat-sheet.html
    - title: Tech Brochure
      url: /assets/tech_brochure.pdf
    - title: Event Rider Sheet
      url: /assets/event_rider_sheet.pdf

drawings:
    - title: Performance Hall East Perspective
      url: /assets/ph_east_perspective.pdf
